version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/14/main 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
  web:
    build: ./code/
    volumes:
      - ./code/:./code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  
volumes:
  postgres_data: