version: "3.9"

services:
  db:
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/
      #environment: ???
        #- POSTGRES_DB=reminderdb
        #- POSTGRES_USER=postgres
        #- POSTGRES_PASSWORD=sml12345
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes
    ports: 
      - "8000:8000"
    depends_on:
      -db
