# Generated by Django 3.2.1 on 2022-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
